services:
  - type: web
    name: nerv-ml-signals-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python run_bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: TG_TOKEN
        sync: false
      - key: TG_CHAT_ID
        sync: false
      - key: PORT
        value: 8000
