services:
  - type: web
    name: nerv-ml-signals-bot
    env: docker
    envVars:
      - key: TG_TOKEN
        sync: false
      - key: TG_CHAT_ID
        sync: false
      - key: PORT
        value: 8000

